_wandb:
    value:
        cli_version: 0.23.1
        e:
            pyqt8b0k4m7443c0i0gmlowhhl7wnz48:
                args:
                    - configs/svg/svg_pointT.yaml
                    - --dist
                    - --exp_name
                    - sympointv1_deneme
                    - --work_dir
                    - /temp/work_dir/
                    - --resume
                    - /content/drive/MyDrive/My_Computer/sympoint_data/svg/best.pth
                codePath: tools/train.py
                codePathLocal: tools/train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "253055008768"
                        used: "56394801152"
                email: kirbiyike22@itu.edu.tr
                executable: /root/micromamba/envs/spv1/bin/python3.8
                git:
                    commit: 11222e342e8ebf806c1d41f87c62679b1559a88b
                    remote: https://EFCK:@github.com/EFCK/Sympoint.git
                gpu: NVIDIA L4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7424
                      memoryTotal: "24152899584"
                      name: NVIDIA L4
                      uuid: GPU-f93b538c-dd7c-94d0-d208-3c49282effdf
                host: 0bf297a479dc
                memory:
                    total: "56863338496"
                os: Linux-6.6.105+-x86_64-with-glibc2.17
                program: tools/train.py
                python: CPython 3.8.20
                root: /content/Sympoint
                startedAt: "2025-12-23T10:00:48.635724Z"
                writerId: pyqt8b0k4m7443c0i0gmlowhhl7wnz48
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 43
            "2":
                - 1
                - 43
            "3":
                - 13
                - 16
            "4": 3.8.20
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 1
dataset:
    value: svg
epochs:
    value: 50
