_wandb:
    value:
        cli_version: 0.23.1
        e:
            95c5oxbo45y70q4xuc8rxtkmvsc81xyb:
                args:
                    - configs/svg/svg_pointT.yaml
                    - --dist
                    - --exp_name
                    - sympointv1_deneme
                    - --work_dir
                    - /temp/work_dir/
                    - --resume
                    - /content/drive/MyDrive/My_Computer/sympoint_data/svg/best.pth
                codePath: tools/train.py
                codePathLocal: tools/train.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "253055008768"
                        used: "57303379968"
                email: kirbiyike22@itu.edu.tr
                executable: /root/micromamba/envs/spv1/bin/python3.8
                git:
                    commit: 9b999c0fd4375f45e08319fcda00489f27e75389
                    remote: https://EFCK:@github.com/EFCK/Sympoint.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-d656db9f-054d-08c6-d6cc-116202b882ee
                host: f078637ca459
                memory:
                    total: "54750429184"
                os: Linux-6.6.105+-x86_64-with-glibc2.17
                program: tools/train.py
                python: CPython 3.8.20
                root: /content/Sympoint
                startedAt: "2025-12-23T10:45:05.604222Z"
                writerId: 95c5oxbo45y70q4xuc8rxtkmvsc81xyb
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 43
            "2":
                - 1
                - 43
            "3":
                - 13
                - 16
                - 61
            "4": 3.8.20
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 1
dataset:
    value: sympointv1_deneme
epochs:
    value: 50
